default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 8?rSjWDd#J5!a4T

development:
  <<: *default
  database: my_blog_app_development
  username: postgres
  password: 8?rSjWDd#J5!a4T

test:
  <<: *default
  database: my_blog_app_test
  username: postgres
  password: 8?rSjWDd#J5!a4T

production:
  <<: *default
  database: my_blog_app_production
  username: postgres
  password: 8?rSjWDd#J5!a4T
